### ISSUE TITLE
Fix spacing in Candidates Profile page

### ISSUE THREAD

**Issue by Xiomara7** [Global-Shapers-San-Juan/tuvotonosedeja#18]
<img width="1282" alt="Screen Shot 2020-09-03 at 4 19 58 PM" src="https://user-images.githubusercontent.com/3449724/92236286-2198a600-ee83-11ea-82b0-d0242649d9c3.png">

**Comment by pedrocruzio** [comment]
I'll take this on. On what size screen are you seeing this bug? @Xiomara7

**Comment by pedrocruzio** [comment]
![Screen Shot 2020-09-05 at 4 07 38 PM](https://user-images.githubusercontent.com/25227327/92312761-ee910800-ef91-11ea-996b-75fcc3de23c2.png)

Potentially found the issue. Left browser is Safari on desktop; right image is Brave browser. Going to explore adding browser specific css.

**Comment by pedrocruzio** [comment]
Issued fixed.
