### ISSUE TITLE
Mobile first UI design 

### ISSUE THREAD

**Issue by Xiomara7** [Global-Shapers-San-Juan/tuvotonosedeja#3]
### Requirements:
- Gobernación: 6 candidatos/as
- Alcaldía de San Juan: 4 candidatos/as
- Legislatura: TBD

### UI Design Mockup
- [Figma project](https://www.figma.com/file/vh3vYlZHWqPHSn4uzCfdXR/Mobile?node-id=0%3A1)

![test](https://user-images.githubusercontent.com/3449724/87483783-96c5c880-c602-11ea-85c9-d2bdfbe48106.gif)

### Other Examples
- [Politico Election Guide](https://www.politico.com/2020-election/candidates-views-on-the-issues/)
- [Siete8Siete Guide](https://siete8siete.com/elecciones/#1476706880742-81bc2b53-cc29)
- [TheSkimm](https://www.theskimm.com/2020)

**Comment by pedrocruzio** [comment]
Waiting for designs for the following icons:

- Preparación / Experiencia
- Desarrollo Económico:
- Energía / Ambiente:
- Educación:
- Salud / COVID:
- Gobernanza / Corrupción:
- Crimen / Seguridad:
- Derechos Civiles

**Comment by pedrocruzio** [comment]
Design has been finalized. Closing issue.
