### ISSUE TITLE
Prepare updated list of candidates

### ISSUE THREAD

**Issue by pedrocruzio** [Global-Shapers-San-Juan/tuvotonosedeja#4]

**Comment by Xiomara7** [comment]
### Candidates
Alexandra Lúgaro
Wanda o Pierluisi (pending primary)
Bhatia, Yulín, o Charlie Delgado (pending primary)
Juan Dalmau
Eliezer Molina
Victor Medina

**Comment by pedrocruzio** [comment]
Updated list:

Alexandra Lúgaro
Pierluisi
Charlie Delgado
Juan Dalmau
Eliezer Molina
Victor Medina

**Comment by Xiomara7** [comment]
@pedrocruzio : [Updated list of candidates](https://docs.google.com/document/d/1tngrk574Wt8M0RQ-kj3rbct4O2i7B0-YZi3_U2YNwts/edit)
